# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Japanese Notes"
license = "MIT"
licenselink = "https://github.com/elusiveunit/jp-notes/blob/master/LICENSE"
description = "Custom theme for the site"
homepage = "https://github.com/elusiveunit/jp-notes"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""
