baseURL = "http://example.com/jp-notes"
languageCode = "en-us"
title = "Japanese notes"
theme = "jp-notes"
disableHugoGeneratorInject = true
disableKinds = [
  "taxonomy",
  "taxonomyTerm",
  "RSS"
]
enableRobotsTXT = true
